runmode: debug               # 开发模式, debug, release, test
addr: :8182                  # HTTP绑定端口
name: apiserver              # API Server的名字
url: http://127.0.0.1:6663   # pingServer函数请求的API服务器的ip:port
max_ping_count: 101           # pingServer函数尝试的次数.
alec:
  file: configFile
  path: ./config.yaml
  name: config.yaml
